#!/bin/bash

VERSION="1.0"
AUTHY_URL="https://api.authy.com"
APP_ROOT=`dirname $0`
CONFIG_FILE="$APP_ROOT/authy-ssh.conf"

export TERM="xterm-256color"
NORMAL=$(tput sgr0)
GREEN=$(tput setaf 2; tput bold)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)

function red() {
    echo -e "$RED$*$NORMAL"
}

function green() {
    echo -e "$GREEN$*$NORMAL"
}

function yellow() {
    echo -e "$YELLOW$*$NORMAL"
}

function require_curl() {
    curl --help 2>&1 > /dev/null

    if [ $? -ne 0 ]
    then
        red "install curl and try again"
        run_shell
    fi
}

function find_sshd_config() {
    if [[ -w /etc/sshd_config ]]
    then
        SSHD_CONFIG="/etc/sshd_config"
    elif [[ -w /etc/ssh/sshd_config ]]
    then
        SSHD_CONFIG="/etc/ssh/sshd_config"
    else
        red "Cannot find sshd_config in your server. Authy SSH will be enabled when you add the ForceCommand to it"
    fi
}

function add_force_command() {
    find_sshd_config
    authy_ssh_command="$1"

    if [[ $SSHD_CONFIG ]]
    then
      yellow "Adding 'ForceCommand ${authy_ssh_command} login' to ${SSHD_CONFIG}"
      uninstall_authy "quiet" # remove previous installations

      echo "ForceCommand ${authy_ssh_command} login" >> ${SSHD_CONFIG}
      echo ""
      red "    MAKE SURE YOU DO NOT MOVE/REMOVE ${authy_ssh_command} BEFORE COMMENTING ForceCommand OUT ON ${SSHD_CONFIG}"
      sleep 5
    fi
}

function install_authy() {
    source="$1"
    dest="$2/authy-ssh"
    if [[ ! $2 ]]
    then
      dest="/usr/local/bin/authy-ssh" # defaults to /usr/local/bin
    fi
    config_file="${dest}.conf"

    if [[ ! -r `dirname $dest` ]]
    then
      red "${dest} is not writable. Try again using sudo"
      return 1
    fi

    yellow "Copying ${source} to ${dest}..."
    cp "${source}" "${dest}"

    yellow "Setting up permissions..."
    chmod 755 $dest

    echo -n "Enter the Authy API key: "
    read  authy_api_key

    if [ ${#authy_api_key} != 32 ]
    then
      red "you have entered a wrong API key"
      return 1
    fi

    yellow "Generating initial config on ${config_file}..."
    echo "banner=Good job! You've securely log-in with Authy." > "${config_file}"
    echo "api_key=${authy_api_key}" >> "${config_file}"
    chmod 644 ${config_file}

    add_force_command "${dest}"

    echo ""
    echo "To enable two-factor authentication on your account type the following command: "
    echo ""

    if [[ $SUDO_USER ]]
    then
      green "   sudo ${dest} enable $SUDO_USER <your-email> <your-country-code> <your-cellphone>"
    else
      green "   sudo ${dest} enable $USER <your-email> <your-country-code> <your-cellphone>"
    fi
    echo ""
    echo "To enable two-factor authentication on user account type: "
    echo ""
    green "   ${dest} enable <local-username> <user-email> <user-cellphone-country-code> <user-cellphone>"
    echo ""
    echo "To uninstall authy type:"
    echo ""
    green "   ${dest} uninstall"
    echo ""
}

function uninstall_authy() {
    find_sshd_config

    if [[ $1 != "quiet" ]]
    then
      yellow "Uninstalling Authy SSH..."
    fi

    echo "SSHD_CONFIG=$SSHD_CONFIG"

    if [[ $SSHD_CONFIG ]]
    then
        sed -ie '/^ForceCommand.*authy-ssh.*/d' $SSHD_CONFIG
    fi

    if [[ $1 != "quiet" ]]
    then
      green "Authy SSH was uninstalled, now you can safely remove ${APP_ROOT}/authy-ssh and $CONFIG_FILE"
    fi
}

function check_config_file() {
    dir=`dirname ${CONFIG_FILE}`
    if [[ ! -r $dir ]]
    then
        red "ERROR: ${dir} cannot be written by $(whoami)"
        return 1
    fi

    if [[ ! -f $CONFIG_FILE ]]
    then
        red "Authy ssh have not been configured" # FIXME: add more info
        return 1
    fi

    if [[ $1 == "writable" && ! -w $CONFIG_FILE ]]
    then
        red "$CONFIG_FILE is not writable. Please try again using sudo"
        exit -1
    fi

    chmod 644 $CONFIG_FILE 2>/dev/null
    return 0
}

# Checks if the API KEY is valid. This function receives one argument which can be:
#   - run: runs a shell even if the test fails.
#   - anything else: exits the command
function check_api_key() {
    default_action=$1
    if [[ $AUTHY_API_KEY == "replace_me" || ! $AUTHY_API_KEY ]]
    then
        red "Cannot find a valid api key"
        case $default_action in
        run)
            run_shell ;;
        *)
            exit 1 ;;
        esac
    fi
}

# Usage: $(read_config banner)
function read_config() {
    key="$1"

    if [[ ! -f $CONFIG_FILE ]]
    then
        echo "ERROR: $config_file couldn't be found"
        run_shell
    fi

    while IFS='=' read -r ckey value
    do
        if [[ $ckey == $key ]]
        then
            echo $value # don't stop the loop to be able to read repeated keys
        fi
    done < $CONFIG_FILE
}

function install_user() {
    local_user=$1
    if [[ !$local_user ]]
    then
        local_user=$(whoami)
    fi

    eval home_path="~$local_user"
    auth_keys="${home_path}/.ssh/authorized_keys"

    if [[ -f $auth_keys ]]
    then
        echo "Installing authy on ${auth_keys}..."
        cp "${auth_keys}" "${auth_keys}.backup.$(date +%F)"
        sed -ie "s/^\(ssh-.*\)$/command=\"$(echo $COMMAND | sed -e 's/[\/&]/\\&/g') login\" \\1/" "${auth_keys}"
        green "authy-ssh was installed on $local_user account"
        yellow "Please verify that you can log in before closing this session"
    else
        yellow "Please add allowed keys to ${auth_keys} and try again"
        return -1
    fi
}

# usage: register_user "local_user" "<email>" "<country-code>" "<cellphone>"
function register_user() {
    local_user=$1
    url="$AUTHY_URL/protected/json/users/new?api_key=${AUTHY_API_KEY} -d user[email]=$2 -d user[country_code]=$3 -d user[cellphone]=$4 -s"

    response=`id ${local_user} 2>/dev/null`
    if [[ $? -ne 0 ]]
    then
        red "$local_user was not found in your system"
        exit 1
    fi

    response=`curl ${url} 2>/dev/null`
    ok=true

    if [[ $response == *cellphone* ]]
    then
        yellow "Cellphone is invalid"
        ok=false
    fi

    if [[ $response == *email* ]]
    then
        yellow "Email is invalid"
        ok=false
    fi

    if [[ $ok == false ]]
    then
        exit 1
    fi

    if [[ $response == *user*id* ]]
    then
        user_id=`echo $response | grep -o '[0-9]\{1,\}'` # match the authy id
        echo "user=$local_user:$user_id" >> $CONFIG_FILE
        green "User was registered"
    elif [[ $response == "invalid key" ]]
    then
        yellow "The api_key value in $CONFIG_FILE is not valid"
    else
        red "Unknown response: $response"
    fi
}

function run_shell() {
    if [ $SSH_ORIGINAL_COMMAND ] # when user runs: ssh server <command>
    then
        $SSH_ORIGINAL_COMMAND
        exit 0
    elif [ $SHELL ] # when user runs: ssh server
    then
        $SHELL
        exit 0
    fi
}

function find_authy_id() {
    for user in `read_config user`
    do
        IFS=":"; declare -a authy_user=($user)
        if [[ ${authy_user[0]} == $USER ]]
        then
            echo ${authy_user[1]}
            return 0
        fi
    done
}

function login() {
    authy_token="$1"
    authy_id=$(find_authy_id)

    url="$AUTHY_URL/protected/json/verify/${authy_token}/${authy_id}?api_key=${AUTHY_API_KEY}"
    response=`curl -sL -w '%{http_code}' '${url}' -o /dev/null`

    if [ $? -ne 0 ] # something went wrong when running the command, let it pass
    then
        red "Error running curl"
        run_shell
    fi

    if [ "$response" == "200" ]
    then
        green $(read_config banner)
        run_shell
    else
        red "Invalid token. try again"
    fi
}

function request_sms() {
    authy_id=$(find_authy_id) # read authy id that matches $USER
    url="$AUTHY_URL/protected/json/sms/${authy_id}?api_key=${AUTHY_API_KEY}"

    response=`curl ${url} 2>/dev/null`

    if [[ $response == *success*true* ]]
    then
        green "SMS message was sent"
    elif [[ $response == *\"enable_sms\"* ]]
    then
        yellow "SMS is not enabled for this account"
    else
        red "Message couldn't be sent: $response"
    fi
}

function run() {
    if [[ ! $(find_authy_id) ]] #user is not using authy, let it go
    then
        run_shell
    fi

    while :
    do
        echo -n "Authy Token (type 'sms' to request a SMS token): "
        read authy_token

        case $authy_token in
            sms) request_sms ;;
            *) login $authy_token ;;
        esac
    done
}

require_curl

# get the absolute path to the command
cd `dirname $0`
COMMAND="$PWD/`basename $0`" 
cd - >/dev/null

case $1 in
    install)
        install_authy $0 $2
        ;;
    uninstall)
        uninstall_authy
        ;;
    enable)
        check_config_file "writable"
        AUTHY_API_KEY="$(read_config api_key)"
        check_api_key "exit"
        register_user $2 $3 $4 $5
        ;;
    login)
        check_config_file
        AUTHY_API_KEY="$(read_config api_key)"
        check_api_key "run"
        run
        ;;
    protect)
        check_config_file
        AUTHY_API_KEY="$(read_config api_key)"
        install_user $2
        ;;
    version)
        echo "Authy SSH v$VERSION"
        exit 0
        ;;
    *)
        cat <<__EOF__
Usage: authy-ssh <command> <arguments>

VERSION $VERSION

Available commands:

    install
        installs Authy SSH in the given directory. This command needs sudo if the directory is not writable.

        sudo authy-ssh install /usr/local/bin

    enable
        receives a list of arguments needed to register a user. usage:

        sudo authy-ssh enable <local-user> <email> <country code> <cellphone>

    protect
        installs authy-ssh for the given user

        authy-ssh protect <local-user>

    login
        ask a token to the user if it is already registered.

    version
        prints the Authy SSH version

__EOF__
        ;;
esac
